on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

name: Build & Test

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and export Docker image
        run: |
          docker build -t trillbot-discord:latest .
          docker save -o /tmp/trillbot-discord.latest.tar trillbot-discord:latest

      - name: Upload Docker image to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: trillbot-discord.latest.tar
          path: /tmp/trillbot-discord.latest.tar
  test:
    name: Test
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Docker image from artifacts
        uses: actions/download-artifact@v2
        with:
          name: trillbot-discord.latest.tar
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/trillbot-discord.latest.tar

      - name: Run pyflakes
        run: |
          docker run trillbot-discord:latest pyflakes .
